import json
import os
import time
import uuid
from io import BytesIO

import pytest


def _bool_env(name: str) -> bool:
    return (os.getenv(name) or "").strip().lower() in {"1", "true", "yes", "on"}


def _make_boto3_client(service: str):
    import boto3
    from botocore.config import Config

    region = os.getenv("AWS_REGION")
    endpoint_url = os.getenv("AWS_ENDPOINT_URL")

    # Keep integration tests snappy and avoid hanging on network issues.
    config = Config(
        connect_timeout=int(os.getenv("AWS_IT_CONNECT_TIMEOUT", "5")),
        read_timeout=int(os.getenv("AWS_IT_READ_TIMEOUT", "10")),
        retries={"max_attempts": int(os.getenv("AWS_IT_MAX_ATTEMPTS", "2")), "mode": "standard"},
    )

    if region and endpoint_url:
        return boto3.client(service, region_name=region, endpoint_url=endpoint_url, config=config)
    if region:
        return boto3.client(service, region_name=region, config=config)
    if endpoint_url:
        return boto3.client(service, endpoint_url=endpoint_url, config=config)
    return boto3.client(service, config=config)


def _require(name: str) -> str:
    val = os.getenv(name)
    if not val:
        raise RuntimeError(f"Missing required env var for integration test: {name}")
    return val


def _receive_and_delete_job_message(sqs, queue_url: str, job_id: str, timeout_s: float = 10.0) -> bool:
    deadline = time.time() + timeout_s
    while time.time() < deadline:
        resp = sqs.receive_message(
            QueueUrl=queue_url,
            MaxNumberOfMessages=10,
            WaitTimeSeconds=1,
            VisibilityTimeout=5,
        )
        for msg in resp.get("Messages") or []:
            receipt = msg.get("ReceiptHandle")
            body = msg.get("Body") or ""
            try:
                payload = json.loads(body)
            except Exception:
                payload = None

            if payload and payload.get("job_id") == job_id:
                sqs.delete_message(QueueUrl=queue_url, ReceiptHandle=receipt)
                return True

            # Not ours: put it back quickly by ending visibility timeout.
            # (We avoid deleting other messages.)
            try:
                sqs.change_message_visibility(QueueUrl=queue_url, ReceiptHandle=receipt, VisibilityTimeout=0)
            except Exception:
                pass

    return False


@pytest.mark.integration
def test_aws_generate_upload_url_and_put_object(tmp_path, monkeypatch):
    if not _bool_env("RUN_AWS_INTEGRATION_TESTS"):
        pytest.skip("Set RUN_AWS_INTEGRATION_TESTS=1 to run AWS integration tests")

    # Safety: never touch your prod DB.
    monkeypatch.setenv("DEBUG", "true")
    monkeypatch.setenv("SQLITE_DB_PATH", str(tmp_path / "integration.db"))

    # Import app after env is set.
    import importlib

    main = importlib.import_module("main")

    from fastapi.testclient import TestClient

    bucket = _require("AWS_S3_BUCKET")

    key_prefix = (os.getenv("AWS_TEST_PREFIX") or "integration-tests").strip().strip("/")
    unique = str(uuid.uuid4())
    filename = f"{key_prefix}/{unique}.mp4"

    with TestClient(main.app) as client:
        resp = client.post(
            "/api/v1/jobs/generate-upload-url",
            json={"store_id": "integration", "filename": filename},
        )
        assert resp.status_code == 200
        data = resp.json()
        assert data["upload_url"].startswith("http")

        # Actually upload to the presigned URL.
        import httpx

        video_bytes = b"\x00\x00\x00\x18ftypmp42\x00\x00\x00\x00mp42isom"  # tiny mp4-ish header
        put = httpx.put(
            data["upload_url"],
            content=video_bytes,
            headers={"Content-Type": "video/mp4"},
            timeout=float(os.getenv("AWS_IT_HTTP_TIMEOUT", "10")),
        )
        assert put.status_code in (200, 204)

    s3 = _make_boto3_client("s3")

    # Key is generated by the API as: uploads/<store>/<jobid>_<filename>
    # We don't know it from the response, so we confirm the presigned PUT created our object by listing prefix.
    # This is why AWS_TEST_PREFIX is recommended.
    listed = s3.list_objects_v2(Bucket=bucket, Prefix=f"uploads/integration/")
    keys = [o["Key"] for o in (listed.get("Contents") or [])]
    assert any(filename in k for k in keys)

    # Cleanup best-effort.
    for k in keys:
        if filename in k:
            s3.delete_object(Bucket=bucket, Key=k)


@pytest.mark.integration
def test_aws_upload_endpoint_puts_s3_and_sends_sqs(tmp_path, monkeypatch):
    if not _bool_env("RUN_AWS_INTEGRATION_TESTS"):
        pytest.skip("Set RUN_AWS_INTEGRATION_TESTS=1 to run AWS integration tests")

    # Safety: never touch your prod DB.
    monkeypatch.setenv("DEBUG", "true")
    monkeypatch.setenv("SQLITE_DB_PATH", str(tmp_path / "integration.db"))

    # Use a dedicated, temporary queue so we don't race other consumers (worker/ECS/etc.).
    sqs = _make_boto3_client("sqs")
    queue_name = f"shelfie-it-{uuid.uuid4()}".replace("_", "-")
    created = sqs.create_queue(QueueName=queue_name)
    queue_url = created["QueueUrl"]

    monkeypatch.setenv("AWS_SQS_QUEUE_URL", queue_url)

    import importlib

    main = importlib.import_module("main")

    from fastapi.testclient import TestClient

    bucket = _require("AWS_S3_BUCKET")

    with TestClient(main.app) as client:
        # Upload a small mp4-ish payload (faster than a full video for integration).
        mp4ish = b"\x00\x00\x00\x18ftypmp42\x00\x00\x00\x00mp42isom" + b"0" * 1024
        resp = client.post(
            "/api/v1/jobs/upload",
            files={"video": ("integration.mp4", BytesIO(mp4ish), "video/mp4")},
            data={"store_id": "integration"},
        )
        assert resp.status_code == 202
        job_id = resp.json()["job_id"]

    # Confirm the job wrote an S3 key into the (sqlite) DB.
    from app.db import SessionLocal
    from app import models

    db = SessionLocal()
    try:
        job = db.get(models.VideoJob, job_id)
        assert job is not None
        s3_key = job.s3_object_key
    finally:
        db.close()

    s3 = _make_boto3_client("s3")

    # Verify object exists.
    s3.head_object(Bucket=bucket, Key=s3_key)

    # Verify SQS got our message (and delete it so worker won't run).
    try:
        assert _receive_and_delete_job_message(sqs, queue_url, job_id, timeout_s=10.0)
    finally:
        # Cleanup object + queue.
        try:
            s3.delete_object(Bucket=bucket, Key=s3_key)
        except Exception:
            pass
        try:
            sqs.delete_queue(QueueUrl=queue_url)
        except Exception:
            pass
